### ISSUE TITLE
Error: Cannot find module 'C:\Users\oscar\db\lk-time-bot-master\server.js'

### ISSUE THREAD

**Issue by oscardobsonbrown** [lk-developers/lk-time-bot#8]
Any idea's where server.js has gone? I downloaded the .zip from the green button in the corner

**Comment by ipmanlk** [comment]
Hey, you need to start the `bot.js` as explained in the [Readme file](https://github.com/lk-developers/lk-time-bot/blob/master/README.md). This project doesn't have a file called `server.js`.

**Comment by oscardobsonbrown** [comment]
I think i fixed it. 
If i run `npm start` if gives me this error
```> lk-time@1.0.0 start C:\Users\user\db\lk-time-bot-master
> node server.js

internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module 'C:\Users\user\db\lk-time-bot-master\server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lk-time@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lk-time@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2019-10-31T01_08_08_059Z-debug.log```

however, if i run `node bot.js` it works

I'll try do a pull request and fix it
